import React,{useCallback,useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import Navbar from './NavbarAdmin'
import {useAuth} from './AdminAuth'
import {apiGet,apiPost,apiPut,apiPatch,apiDelete} from './api'
import './Operations.css'
const money=value=>Number(value||0).toLocaleString('en-IN',{style:'currency',currency:'INR'})
const count=value=>Number(value||0).toLocaleString('en-IN')
const date=value=>value?new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'Not yet'
const initialDates=()=>{const end=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});const d=new Date();d.setDate(d.getDate()-30);return{start:d.toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}),end}}
export function Shell({title,subtitle,children,actions}){return <><Navbar/><main className="ops-main"><header className="ops-heading"><div><p>ATTACH OPERATIONS</p><h1>{title}</h1>{subtitle&&<span>{subtitle}</span>}</div><div className="ops-actions">{actions}</div></header>{children}</main></>}
function Message({error,success}){return error?<div className="ops-alert" role="alert">{error}</div>:success?<div className="ops-success" role="status">{success}</div>:null}
function useData(path,params={}){
  const key=JSON.stringify(params),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0)
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setData(null);apiGet(path,JSON.parse(key),{signal:controller.signal}).then(result=>{if(!controller.signal.aborted)setData(result)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[path,key,revision])
  return {data,error,loading,reload:useCallback(()=>setRevision(v=>v+1),[])}
}
function Dates({value,onChange}){return <div className="ops-dates"><label>From<input type="date" value={value.start} onChange={e=>onChange({...value,start:e.target.value})}/></label><label>To<input type="date" value={value.end} onChange={e=>onChange({...value,end:e.target.value})}/></label></div>}
function Pager({total,page,setPage,limit=50}){return <div className="ops-pagination"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>{count(total)} results, page {page+1} of {Math.max(1,Math.ceil(total/limit))}</span><button disabled={(page+1)*limit>=total} onClick={()=>setPage(page+1)}>Next</button></div>}
function Empty({loading,children='No records match your selection.'}){return <div className="ops-empty">{loading?'Loading...':children}</div>}
function Modal({title,children,onClose}){useEffect(()=>{const key=e=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[onClose]);return <div className="ops-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section role="dialog" aria-modal="true" aria-label={title} className="ops-modal"><header><h2>{title}</h2><button type="button" onClick={onClose} aria-label="Close dialog">✕</button></header>{children}</section></div>}
export function Dashboard(){
  const {user}=useAuth(),[dates,setDates]=useState(initialDates)
  const {data,error,loading,reload}=useData('/manage/dashboard',{branch_id:user?.branch_id,...dates})
  return <Shell title="Overview" subtitle={user?.branch_id?'Your selected branch at a glance':'Every branch, one clear view'} actions={<button onClick={reload}>Refresh</button>}><Dates value={dates} onChange={setDates}/><Message error={error}/>{loading&&!data?<Empty loading/>:data&&<><div className="ops-metrics">{[['Collected sales',money(data.sales.revenue),'Paid sales and delivered cash orders'],['Orders',count(data.sales.orders),`${count(data.sales.pending)} awaiting completion`],['Available stock',count(data.stocks.available),`${count(data.stocks.reserved)} reserved`],['Low stock variants',count(data.stocks.low_stock),'Available quantity of 5 or fewer']].map(([label,value,note])=><article key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</div><div className="ops-quick"><Link to="/products">Add a product</Link><Link to="/import">Import Excel</Link><Link to="/pos">Start a sale</Link><Link to="/stocks">Review stock</Link></div><section className="ops-panel"><h2>Branch performance</h2><div className="ops-table-wrap"><table><thead><tr><th>Branch</th><th>Status</th><th>On hand</th><th>Available</th><th>Orders</th><th>Collected sales</th></tr></thead><tbody>{data.branches.map(row=><tr key={row.id}><td>{row.name}</td><td><span className={`ops-badge ${row.is_active?'':'is-muted'}`}>{row.is_active?'Active':'Inactive'}</span></td><td>{count(row.on_hand)}</td><td>{count(row.available)}</td><td>{count(row.orders)}</td><td>{money(row.revenue)}</td></tr>)}</tbody></table></div></section><section className="ops-panel"><h2>Sales activity</h2><p>India time. Cancelled and failed orders do not count as collected sales.</p><div className="ops-table-wrap"><table><thead><tr><th>Date</th><th>Orders</th><th>Collected sales</th></tr></thead><tbody>{data.daily.map(row=><tr key={row.day}><td>{String(row.day).slice(0,10)}</td><td>{row.orders}</td><td>{money(row.revenue)}</td></tr>)}</tbody></table></div>{!data.daily.length&&<Empty/>}</section></>}</Shell>
}
function downloadCsv(rows,name){const keys=Object.keys(rows[0]||{});const cell=value=>{let text=String(value??'');if(/^[=+@\-\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"'};const blob=new Blob(['\uFEFF'+[keys.map(cell).join(','),...rows.map(row=>keys.map(key=>cell(row[key])).join(','))].join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function StockPage(){
  const {user}=useAuth(),[q,setQ]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0),[low,setLow]=useState(false),[selected,setSelected]=useState(null),[quantity,setQuantity]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
  const {data,error:loadError,loading,reload}=useData('/manage/stock',{branch_id:user?.branch_id,q:search,offset:page*50,low})
  useEffect(()=>setPage(0),[user?.branch_id,search,low])
  const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await apiPatch(`/manage/stock/${selected.variant_id}`,{branch_id:selected.branch_id,on_hand:Number(quantity),expected_on_hand:selected.on_hand,reason});setSelected(null);setSuccess('Stock updated');reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const changeVisibility=async row=>{if(!window.confirm(`${row.is_active?'Hide':'Restore'} ${row.name} in ${row.branch_name}?`))return;setError('');try{if(row.is_active)await apiDelete(`/manage/stock/${row.variant_id}`,{branch_id:row.branch_id});else await apiPatch(`/manage/stock/${row.variant_id}/restore`,{branch_id:row.branch_id});reload()}catch(e){setError(e.message)}}
  const exportRows=async()=>{setBusy(true);try{const all=[];let offset=0,result;do{result=await apiGet('/manage/stock',{branch_id:user?.branch_id,q:search,low,limit:200,offset});all.push(...result.rows);offset+=result.rows.length}while(offset<result.total&&result.rows.length);downloadCsv(all,'branch-stock.csv')}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <Shell title="Stock inventory" subtitle="Quantities stay separate for each branch" actions={<><Link className="ops-primary" to="/products">Add product</Link><button disabled={busy} onClick={exportRows}>Export filtered stock</button></>}><div className="ops-toolbar"><form onSubmit={e=>{e.preventDefault();setSearch(q)}}><input aria-label="Search stock" placeholder="Product, brand, colour or barcode" value={q} onChange={e=>setQ(e.target.value)}/><button>Search</button></form><label><input type="checkbox" checked={low} onChange={e=>setLow(e.target.checked)}/> Low stock only</label><button onClick={reload}>Refresh</button></div><Message error={error||loadError} success={success}/><section className="ops-panel"><div className="ops-table-wrap"><table><thead><tr><th>Product</th><th>Branch</th><th>Variant</th><th>Barcode</th><th>MRP</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Actions</th></tr></thead><tbody>{data?.rows.map(row=><tr key={`${row.branch_id}:${row.variant_id}`}><td><strong>{row.name}</strong><small>{row.brand_name} · {row.category_name}</small></td><td>{row.branch_name}</td><td>{row.colour} / {row.size}<small>Pack of {row.pack_size||1}</small></td><td>{row.ean_code||'No barcode'}</td><td>{money(row.mrp)}</td><td>{row.on_hand}</td><td>{row.reserved}</td><td><span className={`ops-badge ${Number(row.available)<=5?'is-low':''}`}>{row.available}</span></td><td><div className="ops-row-actions"><button onClick={()=>{setSelected(row);setQuantity(row.on_hand);setReason('');setError('')}}>Adjust</button><Link to={`/products?variantId=${row.variant_id}&branchId=${row.branch_id}`}>Edit</Link><button onClick={()=>changeVisibility(row)}>{row.is_active?'Hide':'Restore'}</button></div></td></tr>)}</tbody></table></div>{(!data?.rows.length)&&<Empty loading={loading}/>}<Pager total={data?.total||0} page={page} setPage={setPage}/></section>{selected&&<Modal title={`Adjust ${selected.name}`} onClose={()=>setSelected(null)}><form onSubmit={save} className="ops-form"><p>{selected.branch_name} · {selected.colour} · {selected.size}</p><label>New on-hand quantity<input required type="number" min={selected.reserved} step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Reason<input required minLength="3" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Stock count correction"/></label><Message error={error}/><button className="ops-primary" disabled={busy}>{busy?'Saving...':'Save correction'}</button></form></Modal>}</Shell>
}
const emptyProduct={name:'',brand:'',gender:'WOMEN',category_id:'',pattern:'',fit:'',size:'',colour:'',ean:'',mrp:'',sale_price:'',cost_price:0,b2c_discount_pct:0,b2b_discount_pct:0,quantity:0,pack_size:1,image_url:''}
export function ProductEditor(){
  const {user}=useAuth(),[form,setForm]=useState(emptyProduct),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
  const params=new URLSearchParams(window.location.search),variantId=params.get('variantId'),branchId=params.get('branchId')||user?.branch_id
  const {data}=useData('/categories/admin'),categories=Array.isArray(data)?data:data?.categories||[]
  useEffect(()=>{if(!variantId)return;apiGet(`/manage/products/${variantId}`,{branch_id:branchId}).then(row=>setForm({...emptyProduct,...row,name:row.product_name||row.name,brand:row.brand_name,colour:row.colour,pattern:row.pattern_code||'',ean:row.ean_code||'',quantity:0})).catch(e=>setError(e.message))},[variantId,branchId])
  const field=(key,label,type='text',extra={})=><label>{label}<input type={type} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} {...extra}/></label>
  const save=async e=>{e.preventDefault();setBusy(true);setError('');setSuccess('');try{const body={...form,branch_id:branchId};if(variantId)await apiPut(`/manage/products/${variantId}`,body);else await apiPost('/manage/products',body);setSuccess(variantId?'Product details updated':'Product saved and stock received');if(!variantId)setForm({...form,size:'',colour:'',ean:'',quantity:0})}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <Shell title={variantId?'Edit product':'Add product'} subtitle="One row represents one colour and size. Use the same style code for every variant." actions={<Link to="/import">Bulk import with Excel</Link>}><Message error={error} success={success}/>{!branchId?<Empty>Select a branch in the navigation before adding products.</Empty>:<form className="ops-panel ops-form" onSubmit={save}><h2>1. Product and category</h2><div className="ops-form-grid">{field('name','Product name','text',{required:true,maxLength:180})}{field('brand','Brand name','text',{required:true,maxLength:100})}<label>Department<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value,category_id:''})}>{['WOMEN','MEN','KIDS'].map(v=><option key={v}>{v}</option>)}</select></label><label>Category / subcategory<select required value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Select category</option>{categories.filter(row=>row.gender===form.gender&&Number(row.level)>0&&row.is_active!==false).map(row=><option key={row.id} value={row.id}>{row.category_path||row.path||row.name}</option>)}</select></label>{field('pattern','Style / design code','text',{required:true})}{field('fit','Fit')}</div><h2>2. Colour, size and barcode</h2><div className="ops-form-grid">{field('colour','Colour','text',{required:true})}{field('size','Size','text',{required:true})}{field('ean','Barcode / EAN','text',{required:true,pattern:'[A-Za-z0-9._-]{3,64}'})}{field('pack_size','Pieces per selling pack','number',{min:1,step:1,required:true,disabled:!!variantId})}{field('image_url','Image URL (optional)','text')}</div><h2>3. Price and opening stock</h2><div className="ops-form-grid">{field('mrp','MRP per selling unit','number',{min:.01,step:.01,required:true})}{field('sale_price','Selling price (blank uses MRP)','number',{min:.01,step:.01})}{field('cost_price','Cost per selling unit','number',{min:0,step:.01})}{field('b2c_discount_pct','Retail discount %','number',{min:0,max:100,step:.01})}{field('b2b_discount_pct','Wholesale discount %','number',{min:0,max:100,step:.01})}{!variantId&&field('quantity','Stock to add in selected branch','number',{min:0,step:1,required:true})}</div><p>A discount percentage takes priority over the selling price. Price is per pack when pack size is greater than one. Unknown brands appear as Fashion on the website.</p>{variantId&&<p>Product name and category apply to all variants of this style. Prices apply to this variant in every branch. Use Stock inventory to correct branch quantities.</p>}<div className="ops-actions"><button className="ops-primary" disabled={busy}>{busy?'Saving...':variantId?'Save product':'Save product and stock'}</button><Link to="/stocks">View stock</Link></div></form>}</Shell>
}
export function SalesPage(){
  const {user}=useAuth(),[dates,setDates]=useState(initialDates),[q,setQ]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0),[detail,setDetail]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const {data,error:loadError,loading,reload}=useData('/manage/sales',{branch_id:user?.branch_id,...dates,q:search,offset:page*50})
  useEffect(()=>setPage(0),[user?.branch_id,dates,search])
  const open=async row=>{try{setDetail(await apiGet(`/sales/admin/${row.id}`));setError('')}catch(e){setError(e.message)}}
  const act=async(action)=>{setBusy(true);setError('');setNotice('');try{if(action==='ship'){const result=await apiPost(`/shiprocket/fulfill/${detail.sale.id}`,{});setNotice(`Shipment ready: ${result.shipments?.map(row=>row.awb||row.shipment_id||row.shiprocket_shipment_id||'Pickup pending').join(', ')}`)}else await apiPatch(`/manage/sales/${detail.sale.id}/status`,{status:action});await open(detail.sale);reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const exportRows=async()=>{try{const rows=[];let offset=0,result;do{result=await apiGet('/manage/sales',{branch_id:user?.branch_id,...dates,q:search,offset,limit:200});rows.push(...result.rows.map(({id,branch_name,customer_name,source,status,payment_status,total,created_at})=>({id,branch_name,customer_name,source,status,payment_status,total,created_at})));offset+=result.rows.length}while(offset<result.total&&result.rows.length);downloadCsv(rows,'branch-sales.csv')}catch(e){setError(e.message)}}
  return <Shell title="Sales and orders" subtitle="Online and counter sales, scoped to the selected branch" actions={<><button onClick={reload}>Refresh</button><button onClick={exportRows}>Export filtered sales</button></>}><Dates value={dates} onChange={setDates}/><form className="ops-toolbar" onSubmit={e=>{e.preventDefault();setSearch(q)}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Order ID, customer or status" aria-label="Search sales"/><button>Search</button></form><Message error={error||loadError}/><section className="ops-panel"><div className="ops-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Branch</th><th>Source</th><th>Order status</th><th>Payment</th><th>Total</th><th>Details</th></tr></thead><tbody>{data?.rows.map(row=><tr key={row.id}><td>{String(row.id).slice(0,8)}<small>{date(row.created_at)}</small></td><td>{row.customer_name||'Counter customer'}<small>{row.customer_email}</small></td><td>{row.branch_name||'Unassigned'}</td><td>{row.source}</td><td><span className="ops-badge">{row.status}</span></td><td>{row.payment_status}</td><td>{money(row.total??row.totals?.payable)}</td><td><button onClick={()=>open(row)}>View</button></td></tr>)}</tbody></table></div>{!data?.rows.length&&<Empty loading={loading}/>}<Pager total={data?.total||0} page={page} setPage={setPage}/></section>{detail&&<Modal title={`Order ${String(detail.sale?.id).slice(0,8)}`} onClose={()=>setDetail(null)}><p>{detail.sale?.customer_name} · {detail.sale?.customer_email}</p><p>{detail.sale?.status} · {detail.sale?.payment_status}</p><div className="ops-table-wrap"><table><thead><tr><th>Item</th><th>Variant</th><th>Qty</th><th>Price</th></tr></thead><tbody>{detail.items?.map((row,i)=><tr key={i}><td>{row.product_name}</td><td>{row.colour} / {row.size}</td><td>{row.qty}</td><td>{money(row.price)}</td></tr>)}</tbody></table></div><h3>Delivery address</h3><p>{Object.values(detail.sale?.shipping_address||{}).filter(v=>typeof v==='string').join(', ')||'Counter sale'}</p><strong>Payable: {money(detail.sale?.totals?.payable)}</strong><Message error={error} success={notice}/>{detail.sale?.source==='WEB'&&['PAID','COD'].includes(detail.sale.payment_status)&&!['CANCELLED','DELIVERED','RETURNED'].includes(detail.sale.status)&&<div className="ops-actions">{({PLACED:'PROCESSING',CONFIRMED:'PROCESSING',PROCESSING:'SHIPPED',SHIPPED:'DELIVERED'})[detail.sale.status]&&<button disabled={busy} onClick={()=>act(({PLACED:'PROCESSING',CONFIRMED:'PROCESSING',PROCESSING:'SHIPPED',SHIPPED:'DELIVERED'})[detail.sale.status])}>Mark {({PLACED:'processing',CONFIRMED:'processing',PROCESSING:'shipped',SHIPPED:'delivered'})[detail.sale.status]}</button>}<button disabled={busy} onClick={()=>act('ship')}>Create Shiprocket shipment</button></div>}</Modal>}</Shell>
}
export function ManagementPage({kind}){
  const admins=kind==='admins',{user}=useAuth(),{data,error:loadError,loading,reload}=useData(`/manage/${kind}`),{data:branches}=useData('/manage/branches')
  const [form,setForm]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
  const fresh=()=>setForm(admins?{username:'',name:'',password:'',role_enum:'ADMIN',branch_id:'',is_active:true}:{name:'',code:'',address:'',city:'',state:'',pincode:'',phone:'',email:'',is_active:true})
  const save=async e=>{e.preventDefault();setError('');setBusy(true);try{if(form.id)await apiPut(`/manage/${kind}/${form.id}`,form);else await apiPost(`/manage/${kind}`,form);setForm(null);setSuccess('Saved successfully');reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const deactivate=async row=>{if(!window.confirm(`Deactivate ${row.name||row.username}? Historical records will stay available.`))return;try{await apiDelete(`/manage/${kind}/${row.id}`);reload();setSuccess('Deactivated successfully')}catch(e){setError(e.message)}}
  const field=(key,label,type='text',required=false)=><label>{label}<input type={type} value={form[key]??''} required={required} minLength={key==='password'&&(!form.id||form.password)?10:undefined} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>
  return <Shell title={admins?'Admins and access':'Branches'} subtitle={admins?'Each branch admin can access only their assigned branch':'Manage branch details and availability'} actions={<button className="ops-primary" onClick={fresh}>Create {admins?'admin':'branch'}</button>}><Message error={error||loadError} success={success}/><section className="ops-panel"><div className="ops-table-wrap"><table><thead><tr><th>{admins?'Admin':'Branch'}</th><th>{admins?'Role':'Code'}</th><th>{admins?'Assigned branch':'Location'}</th><th>Status</th><th>{admins?'Last login':'Contact'}</th><th>Actions</th></tr></thead><tbody>{data?.map(row=><tr key={row.id}><td><strong>{row.name||row.username}</strong>{admins&&<small>{row.username}</small>}</td><td>{admins?row.role_enum:row.code}</td><td>{admins?row.branch_name||'All branches':[row.city,row.state].filter(Boolean).join(', ')}</td><td><span className={`ops-badge ${row.is_active?'':'is-muted'}`}>{row.is_active?'Active':'Inactive'}</span></td><td>{admins?date(row.last_login):row.phone}</td><td><div className="ops-row-actions"><button onClick={()=>{setForm({...row,password:''});setError('')}}>Edit</button><button disabled={!row.is_active||(admins&&Number(row.id)===Number(user.id))} onClick={()=>deactivate(row)}>Deactivate</button></div></td></tr>)}</tbody></table></div>{!data?.length&&<Empty loading={loading}/>}</section>{form&&<Modal title={`${form.id?'Edit':'Create'} ${admins?'admin':'branch'}`} onClose={()=>setForm(null)}><form className="ops-form" onSubmit={save}><div className="ops-form-grid">{field('name',admins?'Full name':'Branch name','text',true)}{admins?<>{field('username','Username / email','text',true)}{field('password',form.id?'New password (optional)':'Password','password',!form.id)}<label>Access level<select value={form.role_enum==='SUPER_ADMIN'?'SUPER_ADMIN':'ADMIN'} onChange={e=>setForm({...form,role_enum:e.target.value,branch_id:''})}><option value="ADMIN">Branch admin</option><option value="SUPER_ADMIN">Super admin</option></select></label>{form.role_enum!=='SUPER_ADMIN'&&<label>Branch<select required value={form.branch_id||''} onChange={e=>setForm({...form,branch_id:e.target.value})}><option value="">Select a branch</option>{branches?.filter(b=>b.is_active).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}</>:<>{field('code','Branch code','text',true)}{field('address','Address')}{field('city','City')}{field('state','State')}{field('pincode','PIN code')}{field('phone','Phone')}{field('email','Email','email')}</>}<label>Status<select value={form.is_active?'active':'inactive'} onChange={e=>setForm({...form,is_active:e.target.value==='active'})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><Message error={error}/><button className="ops-primary" disabled={busy}>{busy?'Saving...':'Save changes'}</button></form></Modal>}</Shell>
}
export function MovementsPage(){const {user}=useAuth(),[page,setPage]=useState(0),{data,error,loading}=useData('/manage/movements',{branch_id:user?.branch_id,offset:page*50});return <Shell title="Stock movements" subtitle="A history of receipts, sales and stock corrections"><Message error={error}/><section className="ops-panel"><div className="ops-table-wrap"><table><thead><tr><th>Date</th><th>Branch</th><th>Product</th><th>Change</th><th>Balance</th><th>Reason</th></tr></thead><tbody>{data?.map(row=><tr key={row.id}><td>{date(row.created_at)}</td><td>{row.branch_name}</td><td>{row.product_name}<small>{row.colour} / {row.size}</small></td><td>{Number(row.delta)>0?'+':''}{row.delta}</td><td>{row.balance}</td><td>{row.reason}<small>{row.reference}</small></td></tr>)}</tbody></table></div>{!data?.length&&<Empty loading={loading}/>}<div className="ops-pagination"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1}</span><button disabled={(data?.length||0)<50} onClick={()=>setPage(page+1)}>Next</button></div></section></Shell>}
export function AuditPage(){const {data,error,loading}=useData('/manage/audit');return <Shell title="Activity log" subtitle="The latest 200 administrative changes"><Message error={error}/><section className="ops-panel"><div className="ops-table-wrap"><table><thead><tr><th>When</th><th>Admin</th><th>Action</th><th>Record</th><th>Branch</th></tr></thead><tbody>{data?.map(row=><tr key={row.id}><td>{date(row.created_at)}</td><td>{row.username||row.user_id}</td><td>{row.action}</td><td>{row.entity_id}</td><td>{row.branch_id||'All'}</td></tr>)}</tbody></table></div>{!data?.length&&<Empty loading={loading}/>}</section></Shell>}
export function SettingsPage(){const {logout}=useAuth(),[form,setForm]=useState({old_password:'',new_password:''}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <Shell title="Account settings"><form className="ops-panel ops-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await apiPost('/auth-branch/change-password',form);logout()}catch(e){setMessage(e.message)}finally{setBusy(false)}}}><h2>Change password</h2><p>Changing your password signs you out of all sessions.</p><label>Current password<input type="password" autoComplete="current-password" required value={form.old_password} onChange={e=>setForm({...form,old_password:e.target.value})}/></label><label>New password<input type="password" autoComplete="new-password" required minLength="10" value={form.new_password} onChange={e=>setForm({...form,new_password:e.target.value})}/></label><Message error={message}/><button className="ops-primary" disabled={busy}>Update password</button></form></Shell>}

export function ShippingPage(){
  const {data:branches}=useData('/manage/branches'),{data,error:loadError,reload}=useData('/shiprocket/warehouses'),[form,setForm]=useState({branch_id:'',warehouse_id:'',name:''}),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false)
  const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await apiPut(`/manage/warehouses/${form.branch_id}`,form);setSuccess('Pickup mapping saved');reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <Shell title="Shipping pickups" subtitle="Connect each branch to its exact Shiprocket pickup location"><Message error={error||loadError} success={success}/><form className="ops-panel ops-form" onSubmit={save}><div className="ops-form-grid"><label>Branch<select required value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})}><option value="">Choose a branch</option>{branches?.filter(b=>b.is_active).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Shiprocket pickup ID<input required min="1" type="number" value={form.warehouse_id} onChange={e=>setForm({...form,warehouse_id:e.target.value})}/></label><label>Exact pickup location name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label></div><p>Create or verify the pickup in Shiprocket first. Branch address details come from Branches.</p><button className="ops-primary" disabled={busy}>Save pickup mapping</button></form><section className="ops-panel"><div className="ops-table-wrap"><table><thead><tr><th>Branch</th><th>Pickup name</th><th>Pickup ID</th><th>PIN code</th><th>Action</th></tr></thead><tbody>{data?.map(row=><tr key={row.id}><td>{branches?.find(b=>Number(b.id)===Number(row.branch_id))?.name}</td><td>{row.name}</td><td>{row.warehouse_id}</td><td>{row.pincode}</td><td><button onClick={()=>setForm(row)}>Edit</button></td></tr>)}</tbody></table></div></section></Shell>
}
