import React,{useEffect,useRef,useState} from 'react'
import {Shell} from './Operations'
import {useAuth} from './AdminAuth'
import {apiGet,apiPost} from './api'
const money=n=>Number(n||0).toLocaleString('en-IN',{style:'currency',currency:'INR'})
export default function POS(){
  const {user}=useAuth(),[ean,setEan]=useState(''),[items,setItems]=useState([]),[method,setMethod]=useState('CASH'),[ref,setRef]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState(null),input=useRef(null),requestId=useRef(crypto.randomUUID())
  useEffect(()=>{setItems([]);setReceipt(null);requestId.current=crypto.randomUUID();input.current?.focus()},[user?.branch_id])
  const scan=async e=>{e.preventDefault();if(!ean.trim()||!user?.branch_id)return;setBusy(true);setError('');try{const row=await apiGet(`/barcodes/${encodeURIComponent(ean.trim())}`,{branch_id:user.branch_id});await apiPost('/inventory/scan',{branch_id:user.branch_id,ean_code:ean.trim(),qty:1});setItems(old=>{const found=old.find(v=>v.variant_id===row.variant_id);return found?old.map(v=>v.variant_id===row.variant_id?{...v,qty:v.qty+1}:v):[...old,{...row,qty:1}]});setEan('');setReceipt(null)}catch(e){setError(e.message)}finally{setBusy(false);input.current?.focus()}}
  const total=items.reduce((sum,row)=>sum+Number(row.sale_price??row.mrp)*row.qty,0)
  const pay=async()=>{setBusy(true);setError('');try{const result=await apiPost('/sales/confirm',{branch_id:user.branch_id,sale_id:requestId.current,client_action_id:requestId.current,payment:{method,ref},items:items.map(row=>({variant_id:row.variant_id,qty:row.qty}))});setReceipt(result);setItems([]);setRef('');requestId.current=crypto.randomUUID()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <Shell title="Counter sale" subtitle="Scan items, review quantities, then confirm payment.">{error&&<div className="ops-alert" role="alert">{error}</div>}{receipt&&<div className="ops-success" role="status">Sale completed · {receipt.sale_id} · {money(receipt.total)}</div>}{!user?.branch_id?<div className="ops-empty">Select a branch to start a sale.</div>:<div className="ops-pos-grid"><section className="ops-panel"><form className="ops-toolbar" onSubmit={scan}><input ref={input} aria-label="Barcode" placeholder="Scan or enter barcode" value={ean} onChange={e=>setEan(e.target.value)}/><button disabled={busy}>Add item</button></form><div className="ops-table-wrap"><table><thead><tr><th>Item</th><th>Size / colour</th><th>Price</th><th>Qty</th><th>Action</th></tr></thead><tbody>{items.map(row=><tr key={row.variant_id}><td>{row.product_name}<small>{row.ean_code}</small></td><td>{row.size} / {row.colour}</td><td>{money(row.sale_price??row.mrp)}</td><td><input className="ops-pos-qty" type="number" aria-label={`Quantity for ${row.product_name}`} min="1" step="1" value={row.qty} onChange={e=>setItems(old=>old.map(v=>v.variant_id===row.variant_id?{...v,qty:Math.max(1,Math.floor(Number(e.target.value)||1))}:v))}/></td><td><button disabled={busy} onClick={()=>setItems(old=>old.filter(v=>v.variant_id!==row.variant_id))}>Remove</button></td></tr>)}</tbody></table></div>{!items.length&&<div className="ops-empty">Your sale is empty. Scan the first item.</div>}</section><section className="ops-panel ops-form"><h2>Payment</h2><span>{items.reduce((s,r)=>s+r.qty,0)} selling units</span><strong className="ops-pos-total">{money(total)}</strong><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}><option>CASH</option><option>UPI</option><option>CARD</option></select></label><label>Payment reference<input value={ref} onChange={e=>setRef(e.target.value)}/></label><p>Confirm after receiving payment. Stock and prices are checked again when the sale completes.</p><button className="ops-primary" onClick={pay} disabled={busy||!items.length}>{busy?'Processing...':'Confirm sale'}</button></section></div>}</Shell>
}
